services:
  broker:
    image: eclipse-mosquitto:latest
    ports:
      - '1883:1883'
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - network-broker

  influxdb:
    image: influxdb:1.8
    networks:
      - network-db
      - network-grafana
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - influxdb-data:/var/lib/influxdb
  
  adapter:
    build:
      context: ./adapter 
    image: adapter
    environment:
      - DEBUG_DATA_FLOW=true
    depends_on:
      - broker
      - influxdb
    networks:
      - network-broker
      - network-db

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - network-grafana

  generator:
    image: gitlab.cs.pub.ro:5050/scd/iot-generator
    # image: gitlab.cs.pub.ro:5050/scd/iot-generator:mac for MacOS with ARM
    environment:
      - MQTT_HOST=broker # Change it to your broker DNS
    networks:
      - network-broker # Change as needed


networks:
  network-broker:
    name: network-broker
  network-db:
    name: network-db
  network-grafana:
    name: network-grafana

volumes:
  influxdb-data:
